### ISSUE TITLE
Update Spring Boot to 2.2.1 (or latest available)

### ISSUE THREAD

**Issue by fmendezh** [gbif/gbif-common-ws#9]
In order to keep all our backends up-to-date, we must update all our clients, servers, and ws libraries to the latest possible Spring version (2.2.1 at the moment this issue was created).
This issue was created in this repo but individual tasks must be created on each project, I'd suggest that [metrics-ws ](https://github.com/gbif/metrics/tree/master/metrics-ws)is a good candidate to test newer spring libraries, it has dependencies on Hadoop/HBase, Elasticsearch, Spring Boot and other libraries used by other projects.

**Comment by mike-podolskiy90** [comment]
Let's create a checklist of the projects to be updated and do it on a regular basis

**Comment by mike-podolskiy90** [comment]
Common-ws already uses 2.2.6.
There is a list of Spring releases:
https://github.com/spring-projects/spring-boot/releases
Spring Cloud dependencies should be updated separately

**Comment by mike-podolskiy90** [comment]
https://github.com/gbif/gbif-common-ws/commit/64e708806d7ffc80316eeb443c3ef43934ea135b

**Comment by mike-podolskiy90** [comment]
Use 2.3.7.RELEASE
